-- PostgreSQL/Flyway 基线；SQLite profile 不加载本文件。

CREATE TABLE IF NOT EXISTS customer (id BIGINT PRIMARY KEY, customer_name VARCHAR(64) NOT NULL, phone_masked VARCHAR(32) NOT NULL, level VARCHAR(32), status INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS employee (user_id BIGINT PRIMARY KEY, username VARCHAR(64) UNIQUE NOT NULL, password VARCHAR(128) NOT NULL, display_name VARCHAR(128) NOT NULL, role VARCHAR(32) NOT NULL, group_name VARCHAR(128), skills TEXT, online BOOLEAN NOT NULL DEFAULT TRUE, accepting_tickets BOOLEAN NOT NULL DEFAULT TRUE, max_active_tickets INTEGER NOT NULL DEFAULT 5, enabled BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_employee_role_enabled ON employee(role, enabled);
CREATE TABLE IF NOT EXISTS product (id BIGINT PRIMARY KEY, product_name VARCHAR(128) NOT NULL, category VARCHAR(64), warranty_days INTEGER, returnable BOOLEAN NOT NULL DEFAULT TRUE, status INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS order_info (id BIGINT PRIMARY KEY, order_no VARCHAR(64) UNIQUE NOT NULL, customer_id BIGINT NOT NULL REFERENCES customer(id), product_id BIGINT NOT NULL REFERENCES product(id), order_status VARCHAR(32) NOT NULL, pay_time TIMESTAMPTZ, ship_time TIMESTAMPTZ, sign_time TIMESTAMPTZ, amount NUMERIC(10,2), after_sale_status VARCHAR(32));
CREATE INDEX IF NOT EXISTS idx_order_info_customer ON order_info(customer_id, pay_time DESC);
CREATE TABLE IF NOT EXISTS logistics_info (id BIGINT PRIMARY KEY, order_no VARCHAR(64) UNIQUE NOT NULL REFERENCES order_info(order_no), carrier_name VARCHAR(64) NOT NULL, tracking_no VARCHAR(64) NOT NULL, logistics_status VARCHAR(32) NOT NULL, latest_location VARCHAR(128), estimated_delivery_time TIMESTAMPTZ, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS logistics_trace (id BIGINT PRIMARY KEY, logistics_id BIGINT NOT NULL REFERENCES logistics_info(id), trace_status VARCHAR(32) NOT NULL, trace_desc VARCHAR(255) NOT NULL, location VARCHAR(128), station_name VARCHAR(128), occurred_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_logistics_trace_info_time ON logistics_trace(logistics_id, occurred_at);
CREATE TABLE IF NOT EXISTS support_ticket (id BIGSERIAL PRIMARY KEY, ticket_no VARCHAR(64) UNIQUE, title VARCHAR(128), ticket_type VARCHAR(64), priority VARCHAR(32), customer_id BIGINT NOT NULL REFERENCES customer(id), order_no VARCHAR(64), session_id BIGINT, external_session_no VARCHAR(64), content TEXT, ai_summary TEXT, assigned_group VARCHAR(128), handler_id BIGINT, assigned_by VARCHAR(32), assignment_reason TEXT, assignment_score INTEGER, assigned_at TIMESTAMPTZ, status VARCHAR(32) NOT NULL, sla_deadline TIMESTAMPTZ, source VARCHAR(64), urge_count INTEGER DEFAULT 0, last_urged_at TIMESTAMPTZ, last_urge_reason TEXT, request_id VARCHAR(96), idempotency_key VARCHAR(128), created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uq_support_ticket_request_id ON support_ticket(request_id) WHERE request_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_support_ticket_customer_idempotency ON support_ticket(customer_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_support_ticket_customer_updated ON support_ticket(customer_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_ticket_status_updated ON support_ticket(status, updated_at DESC);
CREATE TABLE IF NOT EXISTS ticket_urge_log (id BIGSERIAL PRIMARY KEY, ticket_no VARCHAR(64) NOT NULL REFERENCES support_ticket(ticket_no), customer_id BIGINT NOT NULL, reason TEXT, created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS idx_ticket_urge_log_ticket_created ON ticket_urge_log(ticket_no, created_at DESC);
